from distutils.command import install_data
import imp
from setuptools import setup
import setuptools

setuptools.setup (
    name="API REST Olivanders",
    version="0.0.1",
    author="alapinilopez",
    author_email="alapinilopez@cifpfbmoll.eu",
    description="API REST Flask practice",
    url="https://github.com/alapinilopez/Olivanders",
    classifiers = [
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    install_requires= [
        "aniso8601 == 9.0.1",
        "attrs == 21.4.0",
        "black == 22.1.0",
        "click == 8.0.4",
        "coverage == 6.3.2",
        "distlib == 0.3.4",
        "filelock == 3.6.0",
        "Flask == 2.0.3",
        "Flask-PyMongo == 2.3.0",
        "iniconfig == 1.1.1",
        "itsdangerous == 2.1.1",
        "Jinja2 == 3.0.3",
        "MarkupSafe == 2.1.0",
        "mypy-extensions == 0.4.3",
        "packaging == 21.3",
        "pathspec == 0.9.0",
        "platformdirs == 2.5.1",
        "pluggy == 1.0.0",
        "py == 1.11.0",
        "pymongo == 4.0.2",
        "pyparsing == 3.0.7",
        "pytest == 7.0.1",
        "pytz == 2021.3",
        "six == 1.16.0",
        "toml == 0.10.2",
        "tomli == 2.0.1",
        "tox == 3.24.5",
        "typing-extensions == 4.1.1",
        "virtualenv == 20.13.3",
        "Werkzeug == 2.0.3",
    ],
)
